/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pkgPresentacion;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import pkgNegocio.Conexion;

/**
 *
 * @author Acer
 */
public class FrmInternalEscritorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmInternalEscritorio
     */
    public FrmInternalEscritorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jEImagePanel1 = new LIB.JEImagePanel();

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Bienvenido,");

        nombre.setForeground(new java.awt.Color(153, 153, 153));
        nombre.setText("Admin.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(491, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jEImagePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImg/recepcion.jpeg"))); // NOI18N

        javax.swing.GroupLayout jEImagePanel1Layout = new javax.swing.GroupLayout(jEImagePanel1);
        jEImagePanel1.setLayout(jEImagePanel1Layout);
        jEImagePanel1Layout.setHorizontalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jEImagePanel1Layout.setVerticalGroup(
            jEImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jEImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEImagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Conexion cn=new Conexion();//para reestablecer la conexion
    Connection con; //para llamar a la cadena de conexion
    PreparedStatement ps; //ejecutar consulta
    ResultSet rs; //almacena datos de la consulta
    //clsEHabitaciones c=new clsEHabitaciones();
    
    
    private void MostrarTabla(){
        ResultSet rs;
        //clsNProducto objNprod = new clsNProducto();
        //DefaultTableModel model = new DefaultTableModel();
        //Object[] dato = new Object[7]; // Cambiamos el tipo de dato a Object
        int li=0,re=0,cli=0;
        ResultSet rpta;
        //String[] dato = new String[1];
//        String sql="SELECT estado FROM tbhabitaciones";
//        try{
//            con=cn.getConnection();
//            ps=con.prepareStatement(sql);
//            rpta=ps.executeQuery();
//            while(rpta.next()){
//                if(rpta.getString(1).equals("Disponible")){
//                    li++;
//                } else if(rpta.getString(1).equals("Reservado")) {
//                    re++;
//                }
//            }
//            lbltotlib.setText(li+"");
//            lbltotres.setText(re+"");
//            rpta = ps.executeQuery("SELECT COUNT(*) AS dni FROM tbusuarios;");
//            while(rpta.next()){
//                cli++;
////                if(!rpta.getString(1).equals("")) {
////                    re++;
////                }
//            }
//            lbltotcli.setText(cli+"");
//        } catch(SQLException e) {
//            //System.out.println("error al Listar"+ex.getMessage());
//            //return rpta=null;
//        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.JEImagePanel jEImagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
